Description:  This template deploys an RDS database in a DB Subnet group that spans
              2 AZs. It imports values from "3-tier-network-module.yaml" and 
              "app-auto-scaling-group-module.yaml"

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: " " 

  DBUsername:
    Description: Enter a username to be used with the RDS database
    Type: String
    Default: admin

  DBPassword:
    Description: Enter a password to be used with the RDS database
    Type: String
    Default: password

Resources:
  DBSubnetGroup:  
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: Subnet group for RDS
      DBSubnetGroupName: db_subnet_group
      SubnetIds:  
        - !ImportValue 3tier-DSubnet1
        - !ImportValue 3tier-DSubnet2

  DBTierSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL from app tier
      GroupName: !Sub ${EnvironmentName}_DBTier_SG

      VpcId: !ImportValue 3tier-VPC
      SecurityGroupIngress:
        - 
          SourceSecurityGroupId: !ImportValue 3tier-ALTSecurityGroup
          FromPort: 3306
          IpProtocol: tcp
          ToPort: 3306

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Sub ${EnvironmentName}_DB
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      DBInstanceClass: db.t3.micro 
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups: [!Ref DBTierSecurityGroup]
      Engine: mysql
      MultiAZ: false
      PubliclyAccessible: false
      StorageType: gp2
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      AllocatedStorage: 20
      MaxAllocatedStorage: 22 